### ISSUE TITLE
CoreUI CDN version has changed, breaking layout

### ISSUE THREAD

**Issue by jternent** [LaravelDaily/laravel-roles-permissions-manager#35]
In admin.blade.php there is no specific version assigned to CoreUI. As of this morning, the CDN is pushing 3.0, last night it was 2.1.16.  This breaks the navbar in the admin layout.

I've tried adding @2.1.16 to the css and js imports for CoreUI, but that does not work -- I may have not done it right because the direct links below seem to work?

It looks like a lot of classes changed between 2.1.x and 3.0, like navbar is now c-navbar.  A full fix would be to find and change all those classes, but a monkeypatch is to download 2.1.16 and change the css and js to local references. 

2.1.16 versions:
https://unpkg.com/@coreui/coreui@2.1.16/dist/css/coreui.min.css
https://unpkg.com/@coreui/coreui@2.1.16/dist/js/coreui.min.js

**Comment by r1tt3r** [comment]
Thanks for the solution.
I downloaded the coreui files to local folders.

**Comment by lokmanm** [comment]
This change just broke all the quickadminpanels with CoreUI theme. This is why its not advisable to use CDN for this kind of stuff. Or maybe they should have used a specific version.

**Comment by PovilasKorop** [comment]
Yes we used CDN directly without specifying the version, sorry guys, lesson for us for the future.

Will patch in all repositories and write explanation/instructions article for all quickadminpanel users and customers tomorrow morning Europe time.

**Comment by PovilasKorop** [comment]
Thanks everybody for reporting this issue, fixed now in two commits:

https://github.com/LaravelDaily/laravel-roles-permissions-manager/commit/77c9906d91530a312d7dc2323f5ec3ccee9b7de5
https://github.com/LaravelDaily/laravel-roles-permissions-manager/commit/7a5f552b4071a05994d97783a00f6e361311f8e3

Also, published an article on our QuickAdminPanel blog, for our users/customers: [For Customers: Replace CoreUI Theme to Use v2.1.16 instead of v3.0](https://quickadminpanel.com/blog/for-customers-replace-coreui-theme-to-use-v2-1-16-instead-of-v3-0/)

Sorry again!
