### ISSUE TITLE
Unable to use bootstrap datepicker

### ISSUE THREAD

**Issue by Gaudwinap** [LaravelDaily/laravel-roles-permissions-manager#39]
I'm trying to use bootstrap date picker but unable to load it. I've attached the error in this. Please help me to fix it.

![datepicker_erro](https://user-images.githubusercontent.com/44316143/80632633-284a8300-8a75-11ea-841a-12fb675790d1.PNG)

**Comment by PovilasKorop** [comment]
@Gaudwinap you probably didn't load jQuery before loading Datpicker.

**Comment by Gaudwinap** [comment]
> @Gaudwinap you probably didn't load jQuery before loading Datpicker.

Sir I used the default datepicker which already used in this package. New datepicker I didn't use. Please guide me where I missed.

![datepicker_error](https://user-images.githubusercontent.com/44316143/80637198-32bc4b00-8a7c-11ea-911f-760b2a123e9c.PNG)

**Comment by PovilasKorop** [comment]
Another idea, from Stackoverflow: "I struggled with a similar problem for hours. It then turned out that jQuery was included twice, once by the program that I was adding a jQuery function to and once by our in-house debugger." - https://stackoverflow.com/questions/1212696/jquery-ui-datepicker-datepicker-is-not-a-function

So maybe somewhere jQuery is included twice in the final code?

**Comment by Gaudwinap** [comment]
> Another idea, from Stackoverflow: "I struggled with a similar problem for hours. It then turned out that jQuery was included twice, once by the program that I was adding a jQuery function to and once by our in-house debugger." - https://stackoverflow.com/questions/1212696/jquery-ui-datepicker-datepicker-is-not-a-function
> 
> So maybe somewhere jQuery is included twice in the final code?

Thanks sir. I replaced my datepicker with this

https://cdnjs.com/libraries/bootstrap-datepicker

Now it is working fine.
